version: 0.2

phases:
  pre_build:
    commands:
      - BUILD_ID=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:10}
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Build id is $BUILD_ID
      - echo Building the Docker image...
      - docker build -t statsd:latest -t statsd:$BUILD_ID .
      - docker tag statsd:latest $ECR:latest
      - docker tag statsd:latest $ECR:$BUILD_ID
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR:latest
      - docker push $ECR:$BUILD_ID